From f47e7bd666aa063d016bdf00ea8f62c97a5b5a7a Mon Sep 17 00:00:00 2001
From: Kevin Backhouse <kevinbackhouse@github.com>
Date: Sat, 17 Jun 2023 13:10:07 +0100
Subject: [PATCH] Fix unit test failure.

(cherry picked from commit 33071f33b2996a3ccbdd51f8cc3b958b5eed0e0b)
---
 unitTests/test_types.cpp | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/unitTests/test_types.cpp b/unitTests/test_types.cpp
index 5cfd80d5e9..b13bbc6825 100644
--- a/unitTests/test_types.cpp
+++ b/unitTests/test_types.cpp
@@ -49,8 +49,8 @@ TEST(DataBuf, canBeConstructedFromExistingData) {
 TEST(DataBuf, tryingToAccessTooFarElementThrows) {
   const std::array<byte, 4> data{'h', 'o', 'l', 'a'};
   DataBuf instance(data.data(), data.size());
-  ASSERT_THROW([[maybe_unused]] auto d = instance.data(4), std::out_of_range);
-  ASSERT_THROW([[maybe_unused]] auto d = instance.c_data(4), std::out_of_range);
+  ASSERT_THROW([[maybe_unused]] auto d = instance.data(5), std::out_of_range);
+  ASSERT_THROW([[maybe_unused]] auto d = instance.c_data(5), std::out_of_range);
 }
 
 TEST(DataBuf, readUintFunctionsWorksOnExistingData) {
